# Generated by Django 4.2.6 on 2023-10-30 11:43

from django.db import migrations, models

import core.services.photo_service


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.photo_service.PhotoService.upload_car_photo),
        ),
    ]
